remote_theme: just-the-docs/just-the-docs
title: My first try
description: Messing around with github pages
baseurl: "/OpenWorkshoptest"
permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"
, "docs/tests/"
]
